### PR TITLE
Add hooks reference

### PR DESCRIPTION
**Pull request by BE-Webdesign**
Adding in a hooks reference.  Covers hooks with the prefix rest_.  If there is a better format desired, let me know and I can revise.

### CODE REVIEW

**Comment by BE-Webdesign** [comment]
Solves #124? Was something else in mind?

**Comment by JasonTheAdams** [comment]
There's something wrong with the markdown, it's not rendering correctly: http://v2.wp-api.org/extending/hooks/

Render Screenshot

**Comment by BE-Webdesign** [comment]
Indeed there is. I think the script was just missing some extra line breaks let me fix that.

**Comment by BE-Webdesign** [comment]
@JasonTheAdams It is fixed.

**Pull request merged**
