### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by vimes1984**

### CODE REVIEW

**Comment by vimes1984** [comment]
fixing a typo :D

**Comment by BE-Webdesign** [comment]
@vimes1984 Thank you.  The docs have for the most part been migrated to developer.wordpress.org. If you are interested in helping out, take a peek there, and see if anything could be improved.

**Comment by vimes1984** [comment]
Thanks Cromley, I'll take a peek now  and see :D

**Comment by vimes1984** [comment]
Also full disclosure I work for  "https://codeable.io/" and if you get any
feature requests we'd be happy to help ;)

**Comment by BE-Webdesign** [comment]
>and if you get any feature requests we'd be happy to help ;)

The REST API is conditionally merged into core and could probably use extra contributors. If you are interested in helping, I recommend joining the WordPress.org slack and hopping into the core-restapi channel meetings where Ryan McCue or K. Adam White could help direct you towards contributions.  This GitHub repo, doesn't really serve a purpose at the moment.

**Pull request merged**
